"""
Generate typst/manifest-parts.typ from index.md link order for poetry/Typst books.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from after_certainty.manuscript.assemble import MD_LINK_RE

SKIP_UNITS = frozenset({"front-matter/title-page.md"})
PROSE_UNITS = frozenset({"front-matter/copyright.md"})


def _manifest_render_call(rel: str, path: str) -> str:
    if rel.endswith("/bridge.md"):
        return f"#part-bridge(render-bridge({path}))"
    if rel.endswith("/closing.md") or rel in PROSE_UNITS:
        return f"#render-prose-markdown({path})"
    return f"#render-markdown({path})"


def _needs_pagebreak_after(rel: str) -> bool:
    if rel.endswith("/bridge.md") or rel.endswith("/closing.md"):
        return False
    return True


def parse_index_markdown_links(index_text: str) -> list[str]:
    rels: list[str] = []
    seen: set[str] = set()
    for line in index_text.splitlines():
        for match in MD_LINK_RE.finditer(line):
            rel = match.group(1).strip()
            if rel in seen:
                continue
            seen.add(rel)
            rels.append(rel)
    return rels


def manifest_lines_for_units(rel_paths: list[str], *, header: str) -> list[str]:
    lines = [
        header,
        "",
        '#import "template.typ": render-markdown, render-prose-markdown, render-bridge',
        '#import "poetry.typ": part-bridge',
        "",
    ]
    for rel in rel_paths:
        if rel in SKIP_UNITS:
            continue
        path = f'"../{rel}"'
        lines.append(_manifest_render_call(rel, path))
        if _needs_pagebreak_after(rel):
            lines.append("#pagebreak()")
        lines.append("")
    return lines


def write_typst_manifest(
    book_dir: Path,
    *,
    header: str = "// Auto-generated by after_certainty.export.typst_manifest",
) -> Path:
    book_dir = book_dir.resolve()
    index = book_dir / "index.md"
    if not index.is_file():
        raise FileNotFoundError(f"Missing index.md: {index}")

    rel_paths = parse_index_markdown_links(index.read_text(encoding="utf-8"))
    if not rel_paths:
        raise ValueError(f"No markdown links found in {index}")

    typst_dir = book_dir / "typst"
    typst_dir.mkdir(parents=True, exist_ok=True)
    out_path = typst_dir / "manifest-parts.typ"
    out_path.write_text(
        "\n".join(manifest_lines_for_units(rel_paths, header=header)), encoding="utf-8"
    )
    return out_path


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--book-dir", required=True, help="Book directory")
    args = parser.parse_args(argv)

    out = write_typst_manifest(Path(args.book_dir))
    print(out.as_posix())


if __name__ == "__main__":
    raise SystemExit(main())
