// Auto-generated by tools/generate_typst_manifest.py

#import "template.typ": render-markdown, render-prose-markdown, render-bridge
#import "poetry.typ": part-bridge

#render-prose-markdown("../front-matter/copyright.md")
#pagebreak()

#render-markdown("../front-matter/introduction.md")
#pagebreak()

#part-bridge(render-bridge("../parts/part-i-what-begins/bridge.md"))

#render-markdown("../parts/part-i-what-begins/what-love-teaches.md")
#pagebreak()

#render-markdown("../parts/part-i-what-begins/when-trust-builds.md")
#pagebreak()

#render-markdown("../parts/part-i-what-begins/how-belief-forms.md")
#pagebreak()

#render-markdown("../parts/part-i-what-begins/why-diversity-matters.md")
#pagebreak()

#render-markdown("../parts/part-i-what-begins/why-collaboration-is-hard.md")
#pagebreak()

#part-bridge(render-bridge("../parts/part-ii-what-forms-together/bridge.md"))

#render-markdown("../parts/part-ii-what-forms-together/what-love-teaches-when-trust-builds-how-belief-forms.md")
#pagebreak()

#render-markdown("../parts/part-ii-what-forms-together/why-collaboration-is-hard-when-trust-builds-and-why-diversity-matters.md")
#pagebreak()

#part-bridge(render-bridge("../parts/part-iii-what-takes-shape/bridge.md"))

#render-markdown("../parts/part-iii-what-takes-shape/when-others-look-to-you.md")
#pagebreak()

#render-markdown("../parts/part-iii-what-takes-shape/how-meaning-moves.md")
#pagebreak()

#part-bridge(render-bridge("../parts/part-iv-what-moves-together/bridge.md"))

#render-markdown("../parts/part-iv-what-moves-together/how-meaning-moves-when-others-look-to-you.md")
#pagebreak()

#render-markdown("../parts/part-iv-what-moves-together/why-diversity-matters-in-how-meaning-moves.md")
#pagebreak()

#render-markdown("../parts/part-iv-what-moves-together/why-diversity-matters-when-others-look-to-you.md")
#pagebreak()

#part-bridge(render-bridge("../parts/part-v-where-they-meet/bridge.md"))

#render-markdown("../parts/part-v-where-they-meet/what-love-teaches-when-others-look-to-you.md")
#pagebreak()

#render-markdown("../parts/part-v-where-they-meet/how-trust-builds-when-others-look-to-you.md")
#pagebreak()

#render-markdown("../parts/part-v-where-they-meet/how-belief-forms-when-others-look-to-you.md")
#pagebreak()

#render-markdown("../parts/part-v-where-they-meet/why-collaboration-is-hard-when-others-look-to-you.md")
#pagebreak()

#part-bridge(render-bridge("../parts/part-vi-what-holds/bridge.md"))

#render-markdown("../parts/part-vi-what-holds/when-trust-builds-how-meaning-moves-and-belief-forms.md")
#pagebreak()

#render-markdown("../parts/part-vi-what-holds/why-collaboration-is-hard-when-trust-builds-how-meaning-moves.md")
#pagebreak()

#render-markdown("../parts/part-vi-what-holds/why-diversity-matters-when-trust-builds-and-others-look-to-you.md")
#pagebreak()

#render-markdown("../parts/part-vi-what-holds/why-collaboration-is-hard-when-trust-builds-how-meaning-moves-when-others-look-to-you.md")
#pagebreak()

#part-bridge(render-bridge("../parts/part-vii-what-remains/bridge.md"))

#render-prose-markdown("../parts/part-vii-what-remains/closing.md")
