#!/usr/bin/env bash
# Publish a prepared release-staging directory as the rolling GitHub release ``latest``.
#
# This script is intentionally small and auditable. It must not run general-purpose
# repository Python build/export code. Callers must supply GH_TOKEN only on this step.
#
# Usage: publish_latest_release.sh <staging-dir> [release-notes]
set -euo pipefail
set +x

staging="${1:-}"
notes="${2:-Automated exports.}"

if [[ -z "$staging" || ! -d "$staging" ]]; then
  echo "usage: $0 <staging-dir> [release-notes]" >&2
  exit 2
fi

if [[ -z "${GH_TOKEN:-}${GITHUB_TOKEN:-}" ]]; then
  echo "GH_TOKEN or GITHUB_TOKEN is required" >&2
  exit 1
fi

shopt -s nullglob
assets=("$staging"/*)
if [[ ${#assets[@]} -eq 0 ]]; then
  echo "No assets in staging directory: $staging" >&2
  exit 1
fi

# Verify checksums when present (generated by preparation job).
if [[ -f "$staging/SHA256SUMS" ]]; then
  (
    cd "$staging"
    sha256sum -c SHA256SUMS
  )
fi

gh release delete latest --yes --cleanup-tag 2>/dev/null || true
gh release create latest \
  --title "Latest book exports" \
  --notes "$notes" \
  "${assets[@]}"
