#!/usr/bin/env python3
"""
Generate typst/manifest-parts.typ from index.md link order for poetry/Typst books.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_TOOLS_DIR = Path(__file__).resolve().parent
_SCRIPTS_DIR = _TOOLS_DIR.parent / "scripts"
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from assemble import MD_LINK_RE  # noqa: E402

SKIP_UNITS = frozenset({"front-matter/title-page.md"})


def parse_index_markdown_links(index_text: str) -> list[str]:
    rels: list[str] = []
    seen: set[str] = set()
    for line in index_text.splitlines():
        for match in MD_LINK_RE.finditer(line):
            rel = match.group(1).strip()
            if rel in seen:
                continue
            seen.add(rel)
            rels.append(rel)
    return rels


def manifest_lines_for_units(rel_paths: list[str], *, header: str) -> list[str]:
    lines = [header, ""]
    for rel in rel_paths:
        if rel in SKIP_UNITS:
            continue
        path = f'"../{rel}"'
        if rel.endswith("/bridge.md"):
            lines.append(f"part-bridge(render-markdown({path}))")
        else:
            lines.append(f"render-markdown({path})")
        if not rel.endswith("/closing.md"):
            lines.append("pagebreak()")
        lines.append("")
    return lines


def write_typst_manifest(
    book_dir: Path,
    *,
    header: str = "// Auto-generated by tools/generate_typst_manifest.py",
) -> Path:
    book_dir = book_dir.resolve()
    index = book_dir / "index.md"
    if not index.is_file():
        raise FileNotFoundError(f"Missing index.md: {index}")

    rel_paths = parse_index_markdown_links(index.read_text(encoding="utf-8"))
    if not rel_paths:
        raise ValueError(f"No markdown links found in {index}")

    typst_dir = book_dir / "typst"
    typst_dir.mkdir(parents=True, exist_ok=True)
    out_path = typst_dir / "manifest-parts.typ"
    out_path.write_text(
        "\n".join(manifest_lines_for_units(rel_paths, header=header)), encoding="utf-8"
    )
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--book-dir", required=True, help="Book directory")
    args = parser.parse_args()

    out = write_typst_manifest(Path(args.book_dir))
    print(out.as_posix())


if __name__ == "__main__":
    main()
