#!/usr/bin/env python3
"""
GitHub Actions helper for issue #116 Phase 3: scaffold enrichment drafts or lint
reports, then open a review PR (no auto-merge, no promote).

Used by ``.github/workflows/semantic-enrichment.yml`` via ``workflow_dispatch``.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_TOOLS_DIR = Path(__file__).resolve().parent
if str(_TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(_TOOLS_DIR))

from propose_semantic_enrichment import propose  # noqa: E402
from semantic_enrichment import (  # noqa: E402
    AGENT_TYPES,
    ENRICHMENT_AGENT_TYPES,
    ENRICHMENT_ROOT,
    REPORT_AGENT_TYPES,
    find_book_dir,
    list_book_entities,
)


def _manual_pr_url(*, base_branch: str, branch: str) -> str | None:
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    server = os.environ.get("GITHUB_SERVER_URL", "https://github.com").rstrip("/")
    if not repo:
        return None
    return f"{server}/{repo}/compare/{base_branch}...{branch}?expand=1"


def _run(
    cmd: list[str], *, cwd: Path, env: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=cwd,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )


def _write_report(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body.rstrip() + "\n", encoding="utf-8")


def _ontology_lint_report(repo: Path, book_id: str) -> Path:
    proc = _run(["make", "lint-semantic-graph"], cwd=repo)
    stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    out = repo / ENRICHMENT_ROOT / book_id / "lint-reports" / f"ontology-lint-{stamp}.md"
    body = (
        f"# Ontology lint report ({book_id})\n\n"
        f"Generated by `make lint-semantic-graph` (exit {proc.returncode}).\n\n"
        f"## stdout\n\n```\n{proc.stdout.strip()}\n```\n\n"
        f"## stderr\n\n```\n{proc.stderr.strip()}\n```\n"
    )
    _write_report(out, body)
    return out


def _discovery_report(repo: Path, book_id: str) -> Path:
    entities = list_book_entities(repo, book_id)
    by_type: dict[str, list[str]] = {}
    for entity_type, slug, _ in entities:
        by_type.setdefault(entity_type, []).append(slug)
    stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    out = repo / ENRICHMENT_ROOT / book_id / "lint-reports" / f"discovery-{stamp}.md"
    lines = [
        f"# Discovery report ({book_id})",
        "",
        "Book-scoped entities (candidates for situational enrichment):",
        "",
    ]
    for entity_type in sorted(by_type):
        lines.append(f"## {entity_type} ({len(by_type[entity_type])})")
        lines.append("")
        for slug in by_type[entity_type][:30]:
            lines.append(f"- `{slug}`")
        if len(by_type[entity_type]) > 30:
            lines.append(f"- … and {len(by_type[entity_type]) - 30} more")
        lines.append("")
    lines.extend(
        [
            "## Suggested follow-ups",
            "",
            "- Run `make infer-semantic-source-links` locally with `--dry-run` for co-mention hints.",
            "- Fill enrichment drafts via `make propose-semantic-enrichment` + agent briefs.",
            "",
        ]
    )
    _write_report(out, "\n".join(lines))
    return out


def collect_enrichment_files(repo: Path, book_id: str, agent_type: str) -> list[Path]:
    root = (repo / ENRICHMENT_ROOT / book_id / agent_type).resolve()
    if not root.is_dir():
        return []
    return sorted(p for p in root.rglob("*") if p.is_file())


def pr_body(
    *,
    repo: Path,
    book_id: str,
    agent_type: str,
    book_dir: Path,
    files: list[Path],
    lint_stdout: str,
) -> str:
    rel_files = [f"- `{p.relative_to(repo)}`" for p in files[:40]]
    if len(files) > 40:
        rel_files.append(f"- … and {len(files) - 40} more files")
    checklist = (
        "- [ ] Drafts reviewed; fill `items` before `make promote-semantic-enrichment`\n"
        "- [ ] `make verify-semantic-ontology` after promote\n"
        "- [ ] See [PR-CHECKLIST.md](docs/agents/semantic/PR-CHECKLIST.md)\n"
    )
    return (
        f"## Summary\n\n"
        f"Semantic agent **`{agent_type}`** for book **`{book_id}`** "
        f"(`{book_dir}`). Part of [#116](https://github.com/ksteffe/after-certainty/issues/116).\n\n"
        f"**Do not auto-merge.** Canonical `semantic/` is unchanged until promote + review.\n\n"
        f"## Files ({len(files)})\n\n"
        + "\n".join(rel_files)
        + "\n\n## Lint (informational)\n\n```\n"
        + lint_stdout.strip()[-4000:]
        + "\n```\n\n## Review checklist\n\n"
        + checklist
    )


def run(
    repo: Path,
    *,
    book_id: str,
    agent_type: str,
    all_entities: bool,
    overwrite: bool,
    base_branch: str,
    dry_run: bool,
    publish: bool = True,
    publish_only: bool = False,
) -> int:
    if agent_type not in AGENT_TYPES:
        print(f"Error: invalid agent_type {agent_type!r}", file=sys.stderr)
        return 2

    book_dir = find_book_dir(repo, book_id)
    book_dir_abs = (repo / book_dir).resolve()

    if not publish_only:
        if agent_type in ENRICHMENT_AGENT_TYPES:
            code = propose(
                repo,
                book_dir=book_dir_abs,
                agent_type=agent_type,
                only_missing=not all_entities,
                overwrite=overwrite,
                dry_run=dry_run,
            )
            if code != 0 and not dry_run:
                print("Warning: propose returned no new scaffolds", file=sys.stderr)
        elif agent_type == "ontology-lint":
            _ontology_lint_report(repo, book_id)
        elif agent_type == "discovery":
            _discovery_report(repo, book_id)

    files = collect_enrichment_files(repo, book_id, agent_type)
    if agent_type in REPORT_AGENT_TYPES:
        files = sorted(
            p for p in (repo / ENRICHMENT_ROOT / book_id / "lint-reports").rglob("*") if p.is_file()
        )
    if not files:
        print("Error: no enrichment output files to commit", file=sys.stderr)
        return 1

    lint_stdout = ""
    if not dry_run and not publish_only:
        lint_proc = _run(["make", "lint-semantic-graph"], cwd=repo)
        lint_stdout = lint_proc.stdout + lint_proc.stderr
        verify_proc = _run(["make", "verify-semantic-ontology"], cwd=repo)
        if verify_proc.returncode != 0:
            print(verify_proc.stdout, file=sys.stderr)
            print(verify_proc.stderr, file=sys.stderr)
            print("Error: verify-semantic-ontology failed", file=sys.stderr)
            return 2
    else:
        lint_stdout = "(skipped)"

    run_id = os.environ.get("GITHUB_RUN_ID", "local")
    branch = f"semantic-agent/{agent_type}-{book_id}-{run_id}"
    title = f"semantic-agent: {agent_type} enrichment for {book_id}"
    body = pr_body(
        repo=repo,
        book_id=book_id,
        agent_type=agent_type,
        book_dir=book_dir,
        files=files,
        lint_stdout=lint_stdout,
    )

    if dry_run or not publish:
        print(f"{'dry-run' if dry_run else 'scaffold-only'}: branch={branch} files={len(files)}")
        if dry_run:
            print(body)
        return 0

    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token:
        print("Error: GH_TOKEN or GITHUB_TOKEN required to open PR", file=sys.stderr)
        return 2

    env = os.environ.copy()
    env["GH_TOKEN"] = token
    git_user = os.environ.get("GIT_AUTHOR_NAME", "github-actions[bot]")
    git_email = os.environ.get(
        "GIT_AUTHOR_EMAIL", "41898282+github-actions[bot]@users.noreply.github.com"
    )

    steps: list[list[str]] = [
        ["git", "config", "user.name", git_user],
        ["git", "config", "user.email", git_email],
        ["git", "checkout", "-b", branch],
    ]
    for cmd in steps:
        proc = _run(cmd, cwd=repo, env=env)
        if proc.returncode != 0:
            print(proc.stderr, file=sys.stderr)
            return proc.returncode

    rel_paths = [str(p.relative_to(repo)) for p in files]
    add_proc = _run(["git", "add", "-f", *rel_paths], cwd=repo, env=env)
    if add_proc.returncode != 0:
        print(add_proc.stderr, file=sys.stderr)
        return add_proc.returncode

    commit_msg = f"semantic-agent: {agent_type} drafts for {book_id}\n\nPart of #116."
    commit_proc = _run(["git", "commit", "-m", commit_msg], cwd=repo, env=env)
    if commit_proc.returncode != 0:
        print(commit_proc.stderr, file=sys.stderr)
        return commit_proc.returncode

    push_proc = _run(["git", "push", "origin", branch], cwd=repo, env=env)
    if push_proc.returncode != 0:
        print(push_proc.stderr, file=sys.stderr)
        return push_proc.returncode

    body_path = repo / "build" / "semantic-enrichment-pr-body.md"
    body_path.parent.mkdir(parents=True, exist_ok=True)
    body_path.write_text(body, encoding="utf-8")

    pr_proc = _run(
        [
            "gh",
            "pr",
            "create",
            "--base",
            base_branch,
            "--head",
            branch,
            "--title",
            title,
            "--body-file",
            str(body_path),
        ],
        cwd=repo,
        env=env,
    )
    if pr_proc.returncode != 0:
        err = (pr_proc.stdout + pr_proc.stderr).strip()
        print(err, file=sys.stderr)
        blocked = (
            "createPullRequest" in err or "not permitted to create or approve pull requests" in err
        )
        manual = _manual_pr_url(base_branch=base_branch, branch=branch)
        if blocked:
            print(
                "Note: automatic PR creation may be disabled. Prefer opening a PR "
                "manually from the compare URL below. Do not enable "
                '"Allow GitHub Actions to create and approve pull requests" unless '
                "you intentionally need Actions to create PRs (approval is separate "
                "and should remain human-only).",
                file=sys.stderr,
            )
        if push_proc.returncode == 0 and manual:
            print(f"Branch pushed. Open a PR manually: {manual}")
            print(f"::notice title=Open PR manually::{manual}")
            return 0
        return pr_proc.returncode

    print(pr_proc.stdout.strip())
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".", help="Repository root")
    parser.add_argument("--book-id", required=True, help="book.id from book.yml")
    parser.add_argument("--agent-type", required=True, help="Agent type")
    parser.add_argument("--base-branch", default="main", help="PR base branch")
    parser.add_argument("--all-entities", action="store_true", help="Scaffold all book entities")
    parser.add_argument("--overwrite", action="store_true", help="Replace existing draft files")
    parser.add_argument("--dry-run", action="store_true", help="Generate files only; no git/gh")
    parser.add_argument(
        "--scaffold-only",
        action="store_true",
        help="Write enrichment files and stop (no GH_TOKEN required)",
    )
    parser.add_argument(
        "--publish-only",
        action="store_true",
        help="Commit/push/open PR for existing drafts only (requires GH_TOKEN)",
    )
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    sys.exit(
        run(
            repo,
            book_id=args.book_id.strip(),
            agent_type=args.agent_type.strip(),
            all_entities=args.all_entities,
            overwrite=args.overwrite,
            base_branch=args.base_branch.strip(),
            dry_run=args.dry_run,
            publish=not args.scaffold_only,
            publish_only=args.publish_only,
        )
    )


if __name__ == "__main__":
    main()
